services:

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"

    volumes:
      - kafka-data:/var/lib/kafka/data

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # IMPORTANT FOR SINGLE NODE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
      
  jobmanager:
    image: flink:1.18
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager

    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-savepoints:/opt/flink/savepoints

    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

    depends_on:
      - kafka

  taskmanager:
    image: flink:1.18
    container_name: flink-taskmanager
    command: taskmanager

    volumes:
      - flink-checkpoints:/opt/flink/checkpoints
      - flink-savepoints:/opt/flink/savepoints

    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

    depends_on:
      - jobmanager
      - kafka

volumes:
  kafka-data:
  flink-checkpoints:
  flink-savepoints: